spring.datasource.url: jdbc:mysql://seralock-db.cwhxcgdndstk.us-east-2.rds.amazonaws.com:3306/evntmgmt_india
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.username: evntmgmt-india
spring.datasource.password: Dbdev@Enfec14
spring.datasource.hikari.connection-timeout: 20000
spring.datasource.hikari.minimum-idle: 5
spring.datasource.hikari.maximum-pool-size: 3


